// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ingredient } from "./Ingredient";
import type { Step } from "./Step";

export interface GetRecipe {
  id: bigint;
  name: string;
  description: string | null;
  image_url: string | null;
  servings: bigint | null;
  time_needed: bigint | null;
  ingredients: Array<Ingredient>;
  steps: Array<Step>;
  author: string;
  created_at: bigint;
}
