// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Recipe {
  id: bigint;
  name: string;
  description: string | null;
  image_url: string | null;
  servings: bigint | null;
  time_needed: bigint | null;
  author: string;
  created_at: bigint;
}
