// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Ingredient {
  id: bigint;
  name: string;
  description: string | null;
  author: string;
  created_at: bigint;
}
