// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PostIngredientAssociation {
  ingredient_id: number
  amount: number | null
  amount_unit: string | null
}
