// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostIngredientAssociation } from "./PostIngredientAssociation";
import type { PostRecipeMetadata } from "./PostRecipeMetadata";
import type { Step } from "./Step";

export interface PostRecipe {
  steps: Array<Step>;
  ingredients: Array<PostIngredientAssociation>;
  metadata: PostRecipeMetadata;
}
