// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PostRecipeMetadata {
  name: string;
  description: string | null;
  image_url: string | null;
  servings: bigint | null;
  work_time: bigint | null;
  wait_time: bigint | null;
}
