// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostIngredientAssociation } from "./PostIngredientAssociation";
import type { Step } from "./Step";

export interface PostRecipe {
  steps: Array<Step>;
  ingredients: Array<PostIngredientAssociation>;
  name: string;
  description: string | null;
  image_url: string | null;
  servings: bigint | null;
  work_time: bigint | null;
  wait_time: bigint | null;
}
