// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsedIngredient } from './UsedIngredient'

export interface Recipe {
  ingredients: Array<UsedIngredient>
  steps: Array<string>
  id: number
  name: string
  description: string | null
  image_url: string | null
  servings: number | null
  work_time: number | null
  wait_time: number | null
  author: string
  created_at: number
}
