// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecipeMetadata } from "./RecipeMetadata";
import type { Step } from "./Step";
import type { UsedIngredient } from "./UsedIngredient";

export interface Recipe {
  ingredients: Array<UsedIngredient>;
  steps: Array<Step>;
  metadata: RecipeMetadata;
}
