// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Review {
  id: number;
  recipe_id: number;
  text: string;
  author: string;
  created_at: number;
}
