// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UsedIngredient {
  amount: number | null;
  amount_unit: string | null;
  id: number;
  name: string;
  description: string | null;
  author: string;
  created_at: number;
}
